[package]
name = "rba_manager"
version = "0.1.0"
authors = ["sujanan <sujananbhathiya@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.4"
serde = "1.0.83"
serde_derive = "1.0.83"
toml = "0.4.10"
ctrlc = { version = "3.0", features = ["termination"] }
